version: '3'

volumes:
  static:
  database:

services:
  HelloDjangoV2:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: hellodjangov2 
    container_name: hellodjangov2 
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
  
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: hellodjangov2_nginx
    container_name: hellodjangov2_nginx
    volumes:
      - static:/apps/HelloDjangoV2/static
    ports:
      - "80:80"
      - "443:443"
  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: hellodjangov2_elasticsearch
    container_name: hellodjangov2_elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536