version: '3'

volumes:
  static:
  database:

services:
  HelloDjangoV2:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: hellodjangov2 
    container_name: hellodjangov2 
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: hellodjangov2_nginx
    container_name: hellodjangov2_nginx
    volumes:
      - static:/apps/HelloDjangoV2/static
    ports:
      - "80:80"
      - "443:443"